
version: '3.3'
services:

    web:
        build : ./
        container_name: webApi
        restart: always
        privileged: true
        ports:
          - "80:80"
        links:
          - db
        volumes:
          - ./:/var/www/src
        environment:
            ENABLE_ENV_FILE: 1
            TZ: America/Mexico_City

    db:
        image: mysql:8.0
        container_name: dbApi
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
          - "3306:3306"
        environment:
              TZ: America/Mexico_City
              MYSQL_ROOT_PASSWORD: 12345
              MYSQL_DATABASE: apiDB
              MYSQL_USER: api
              MYSQL_PASSWORD: secret

    adminer:
        image: adminer
        links:
          - db
        restart: always
        ports:
          - 8090:8080
