
version: '3.3'
services:

    web:
        build : ./
        container_name: webApi
        restart: unless-stopped
        privileged: true
        ports:
          - "8080:80"
        links:
          - db
        volumes:
          - ./:/var/www/src
        environment:
            ENABLE_ENV_FILE: 1
            TZ: America/Mexico_City

    db:
        image: mysql:5.7
        container_name: dbApi
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        ports:
          - "3306:3306"
        environment:
              TZ: America/Mexico_City
              MYSQL_ROOT_PASSWORD: 12345
              MYSQL_DATABASE: apiDB
              MYSQL_USER: api
              MYSQL_PASSWORD: secret

    # adminer:
    #     image: adminer
    #     links:
    #       - db
    #     restart: always
    #     ports:
    #       - 8090:8080
